=== milos321/BSEP2016/repoPrj - certs/xsd/amandman.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/amandman"
    xmlns:ama="http://www.ftn.uns.ac.rs/amandman">
    <xs:element name="Amandman">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" name="Kome">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element default="PREDSEDNIK NARODNE SKUPSTINE" name="Naslov"
                                type="xs:string"/>
                            <xs:element name="Informacije">
                                <xs:complexType mixed="true">
                                    <xs:all>
                                        <xs:element default="xs:string"
                                            name="NazivPropisaKojiSeMenja"/>
                                        <xs:element
                                            name="BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst"
                                            type="xs:string"/>
                                        <xs:element maxOccurs="1" minOccurs="0"
                                            name="BrojeviSvihSluzbenihGlasila" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Opis">
                    <xs:complexType mixed="false">
                        <xs:sequence>
                            <xs:element default="AMANDMAN" name="Naslov" type="xs:string"/>
                            <xs:element maxOccurs="unbounded" name="Detalji" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                        <xs:choice>
                                            <xs:element name="Clan" type="xs:integer"/>
                                            <xs:element name="Stav" type="xs:integer"/>
                                            <xs:element name="Tacka" type="xs:integer"/>
                                            <xs:element name="Podtacka" type="xs:integer"/>
                                            <xs:element name="BriseSe">
                                                <xs:complexType>
                                                  <xs:choice>
                                                  <xs:element default="" name="BezReci"
                                                  type="xs:string"/>
                                                  <xs:element name="Rec" type="xs:string"/>
                                                  </xs:choice>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="MenjaSe">
                                                <xs:complexType mixed="true">
                                                  <xs:choice>
                                                  <xs:element default="" name="tekstOdredbe"
                                                  type="xs:string"/>
                                                  <xs:sequence>
                                                  <xs:element name="prvaRec" type="xs:string"/>
                                                  <xs:element name="DrugaRec" type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:choice>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:choice>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Obrazlozenje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Naslov" type="xs:string"/>
                            <xs:element name="TekstObrazlozenja" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Predlagac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Funkcija" type="xs:string"/>
                            <xs:element name="Naziv" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== milos321/BSEP2016/XML_Security/xml/amandman.xml
<?xml version="1.0" encoding="UTF-8"?>
<Amandman xmlns="http://www.ftn.uns.ac.rs/amandman"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/amandman file:/C:/Users/Milos/Documents/busep/schema/amandman.xsd">
    <Kome>
        <Naslov></Naslov>
        <Informacije>
            <NazivPropisaKojiSeMenja></NazivPropisaKojiSeMenja>
            <BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst></BrojSluzbenogGlasilaUKojemJeObjavljenOsnovniTekst>
        </Informacije>
    </Kome>
    <Opis>
        <Naslov></Naslov>
    </Opis>
    <Obrazlozenje>
        <Naslov></Naslov>
        <TekstObrazlozenja></TekstObrazlozenja>
    </Obrazlozenje>
    <Predlagac>
        <Funkcija></Funkcija>
        <Naziv></Naziv>
    </Predlagac>
</Amandman>
